apiVersion: v1
kind: Service
metadata:
  labels:
    app: queue
  name: fleetman-queue
spec:
  ports:
    - name: http
      port: 8161
      protocol: TCP
      targetPort: 8161
      nodePort: 30080

    - name: endpoint
      port: 61616
      protocol: TCP
      targetPort: 61616
      nodePort: 30010
  selector:
    app: queue
  type: NodePort
status:
  loadBalancer: {}